let questoes=[],filtradas=[],simulado=[],atual=0,respostas=[],inicio=null,timer=null,limiteLista=30;
const $=s=>document.querySelector(s);const STORE='pm_banco_cg_v3';const state=JSON.parse(localStorage.getItem(STORE)||'{"respondidas":0,"acertos":0,"erradas":[],"favoritas":[]}');
function save(){localStorage.setItem(STORE,JSON.stringify(state));stats()}function tela(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');scrollTo(0,0)}function uniq(a){return[...new Set(a.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'pt-BR',{numeric:true}))}function normal(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
async function carregar(){try{const r=await fetch('data/questoes.json');if(!r.ok)throw new Error();questoes=await r.json();filtradas=[...questoes];filtros();listar();stats()}catch(e){$('#listaQuestoes').innerHTML='<p>Não foi possível carregar o banco. Atualize a página ou verifique o arquivo data/questoes.json.</p>'}}
function filtros(){uniq(questoes.map(q=>q.tema)).forEach(v=>{$('#tema').add(new Option(v,v));$('#temaSimulado').add(new Option(v,v))});uniq(questoes.map(q=>q.ano)).reverse().forEach(v=>$('#ano').add(new Option(v,v)))}
function stats(){$('#totalQuestoes').textContent=questoes.length.toLocaleString('pt-BR');$('#respondidas').textContent=state.respondidas.toLocaleString('pt-BR');$('#acertos').textContent=state.acertos.toLocaleString('pt-BR');$('#percentual').textContent=state.respondidas?Math.round(state.acertos/state.respondidas*100)+'%':'0%'}
function listar(reset=true){if(reset)limiteLista=30;const a=filtradas.slice(0,limiteLista);$('#contadorLista').textContent=`${filtradas.length.toLocaleString('pt-BR')} resultado(s)`;$('#listaQuestoes').innerHTML=a.length?a.map(q=>`<article class="list-item" data-id="${q.id}"><strong>Questão ${q.id}</strong><p>${esc(q.enunciado).slice(0,230)}${q.enunciado.length>230?'...':''}</p><div class="chips"><span class="chip">${esc(q.tema)}</span><span class="chip">${esc(q.orgao||'Órgão não informado')}</span><span class="chip">${q.ano||'s/ano'}</span><span class="chip">p. ${q.pagina||'-'}</span></div></article>`).join(''):'<p>Nenhuma questão encontrada.</p>';document.querySelectorAll('.list-item').forEach(e=>e.onclick=()=>iniciar([questoes.find(q=>q.id==e.dataset.id)]));$('#maisBtn').classList.toggle('hidden',limiteLista>=filtradas.length)}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function pesquisar(){const t=normal($('#busca').value),tema=$('#tema').value,ano=$('#ano').value,d=$('#dificuldade').value;filtradas=questoes.filter(q=>(!t||normal([q.enunciado,q.tema,q.subtema,q.cargo,q.orgao,q.ano,q.comentario,Object.values(q.alternativas||{}).join(' ')].join(' ')).includes(t))&&(!tema||q.tema===tema)&&(!ano||String(q.ano)===ano)&&(!d||q.dificuldade===d));listar()}
function embaralhar(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function iniciar(a){if(!a.length)return alert('Nenhuma questão disponível para esta seleção.');simulado=a;atual=0;respostas=[];inicio=Date.now();clearInterval(timer);timer=setInterval(crono,1000);mostrar();tela('quiz')}
function gerar(){let a=questoes,t=$('#temaSimulado').value;if(t)a=a.filter(q=>q.tema===t);iniciar(embaralhar(a).slice(0,Math.min(Number($('#quantidade').value),a.length)))}
function mostrar(){const q=simulado[atual];$('#progresso').textContent=`${atual+1} de ${simulado.length}`;$('#meta').textContent=`${q.banca||'FGV'} • ${q.orgao||'Órgão não informado'} • ${q.ano||'s/ano'} • ${q.tema||'Tema não informado'} • página ${q.pagina||'-'}`;$('#enunciado').textContent=q.enunciado;$('#alternativas').innerHTML=Object.entries(q.alternativas||{}).map(([l,t])=>`<button class="alternative" data-l="${l}"><b>${l})</b> ${esc(t)}</button>`).join('');document.querySelectorAll('.alternative').forEach(b=>b.onclick=()=>responder(b.dataset.l));$('#favoritarAtual').textContent=state.favoritas.includes(q.id)?'★ Favoritada':'☆ Favoritar'}
function responder(l){const q=simulado[atual],c=l===q.gabarito;respostas.push({id:q.id,marcada:l,gabarito:q.gabarito,certa:c});state.respondidas++;if(c)state.acertos++;else if(!state.erradas.includes(q.id))state.erradas.push(q.id);save();$('#statusResposta').className='answer-status '+(c?'correct':'wrong');$('#statusResposta').textContent=c?'✅ VOCÊ ACERTOU':'❌ VOCÊ ERROU';$('#resumoResposta').innerHTML=c?`Resposta correta: <b>${esc(q.gabarito)}</b>`:`Sua resposta: <b>${esc(l)}</b><br>Resposta correta: <b>${esc(q.gabarito)}</b>`;$('#comentario').innerHTML=q.comentario||'<p>Comentário não disponível.</p>';tela('resultado')}
function proxima(){atual++;atual>=simulado.length?finalizar():(mostrar(),tela('quiz'))}function finalizar(){clearInterval(timer);const a=respostas.filter(r=>r.certa).length;$('#resultadoFinal').innerHTML=`${a}/${simulado.length}<div style="font-size:20px;color:#555">${Math.round(a/simulado.length*100)}% de acertos</div>`;tela('final')}function crono(){const s=Math.floor((Date.now()-inicio)/1000),h=String(Math.floor(s/3600)).padStart(2,'0'),m=String(Math.floor(s%3600/60)).padStart(2,'0'),x=String(s%60).padStart(2,'0');$('#cronometro').textContent=`${h}:${m}:${x}`}
$('#pesquisarBtn').onclick=pesquisar;$('#busca').oninput=pesquisar;$('#tema').onchange=pesquisar;$('#ano').onchange=pesquisar;$('#dificuldade').onchange=pesquisar;$('#iniciarBtn').onclick=gerar;$('#listarBtn').onclick=()=>{filtradas=[...questoes];listar()};$('#maisBtn').onclick=()=>{limiteLista+=30;listar(false)};$('#erradasBtn').onclick=()=>{const a=questoes.filter(q=>state.erradas.includes(q.id));a.length?iniciar(a):alert('Nenhuma questão errada registrada.')};$('#favoritasBtn').onclick=()=>{filtradas=questoes.filter(q=>state.favoritas.includes(q.id));filtradas.length?listar():alert('Nenhuma questão favoritada.')};$('#limparBtn').onclick=()=>{if(confirm('Deseja apagar todo o seu progresso, favoritos e caderno de erros?')){state.respondidas=0;state.acertos=0;state.erradas=[];state.favoritas=[];save();alert('Progresso apagado.')}};$('#sairBtn').onclick=()=>{clearInterval(timer);tela('home')};$('#proximaBtn').onclick=proxima;$('#voltarInicioBtn').onclick=()=>tela('home');$('#revisarSimuladoBtn').onclick=()=>{const ids=respostas.filter(r=>!r.certa).map(r=>r.id),a=simulado.filter(q=>ids.includes(q.id));a.length?iniciar(a):alert('Você não errou nenhuma questão neste simulado.')};$('#favoritarAtual').onclick=()=>{const id=simulado[atual].id,i=state.favoritas.indexOf(id);i>=0?state.favoritas.splice(i,1):state.favoritas.push(id);save();mostrar()};
let deferredPrompt;addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')}};if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js'));carregar();